/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Automatic device detection activated": {        "en": "Automatic device detection activated",            "de": "Automatische Geräteerkennung aktiviert",          "ru": "Активировано автоматическое обнаружение устройства", "pt": "Detecção automática de dispositivo ativada",      "nl": "Automatische apparaatherkenning geactiveerd",     "fr": "Détection automatique des appareils activée",     "it": "Rilevamento automatico del dispositivo attivato", "es": "Detección automática de dispositivos activada",   "pl": "Aktywowane automatyczne wykrywanie urządzeń",     "zh-cn": "自动设备检测已激活"},
    "Connected": {                                   "en": "Connected",                                       "de": "In Verbindung gebracht",                          "ru": "Связаны",                                         "pt": "Conectado",                                       "nl": "Verbonden",                                       "fr": "Lié",                                             "it": "Collegato",                                       "es": "Conectado",                                       "pl": "Połączony",                                       "zh-cn": "连接的"},
    "Delete": {                                      "en": "Delete",                                          "de": "Löschen",                                         "ru": "Удалить",                                         "pt": "Excluir",                                         "nl": "Verwijderen",                                     "fr": "Effacer",                                         "it": "Elimina",                                         "es": "Borrar",                                          "pl": "Kasować",                                         "zh-cn": "删除"},
    "Devices can be added manually or by autodiscovery": {"en": "Devices can be added manually or by auto-discovery", "de": "Geräte können manuell oder durch automatische Erkennung hinzugefügt werden", "ru": "Устройства можно добавлять вручную или с помощью автообнаружения", "pt": "Os dispositivos podem ser adicionados manualmente ou por autodiscovery", "nl": "Apparaten kunnen handmatig of door autodiscovery worden toegevoegd", "fr": "Les appareils peuvent être ajoutés manuellement ou par découverte automatique", "it": "I dispositivi possono essere aggiunti manualmente o tramite rilevamento automatico", "es": "Los dispositivos se pueden agregar manualmente o por descubrimiento automático", "pl": "Urządzenia można dodawać ręcznie lub przez automatyczne wykrywanie", "zh-cn": "可以手动添加设备或通过自动发现添加设备"},
    "ID": {                                          "en": "ID",                                              "de": "ICH WÜRDE",                                       "ru": "Я БЫ",                                            "pt": "EU IA",                                           "nl": "ID",                                              "fr": "identifiant",                                     "it": "ID",                                              "es": "IDENTIFICACIÓN",                                  "pl": "ID",                                              "zh-cn": "ID"},
    "IP-Address": {                                  "en": "IP Address",                                      "de": "IP Adresse",                                      "ru": "Айпи адрес",                                      "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "Имя",                                             "pt": "Nome",                                            "nl": "Naam",                                            "fr": "Nom",                                             "it": "Nome",                                            "es": "Nombre",                                          "pl": "Nazwa",                                           "zh-cn": "姓名"},
    "reconnect interval": {                          "en": "Reconnect Interval",                              "de": "Intervall für erneutes Verbinden",                "ru": "интервал повторного подключения",                 "pt": "intervalo de reconexão",                          "nl": "interval voor opnieuw verbinden",                 "fr": "intervalle de reconnexion",                       "it": "ricollegare l'intervallo",                        "es": "intervalo de reconexión",                         "pl": "interwał ponownego łączenia",                     "zh-cn": "重新连接间隔"},
};