/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "API password": {                                "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Add device manually": {                         "en": "Add device manually",                             "de": "Gerät manuell hinzufügen",                        "ru": "Добавить устройство вручную",                     "pt": "Adicionar dispositivo manualmente",               "nl": "Voeg apparaat handmatig toe",                     "fr": "Ajouter un appareil manuellement",                "it": "Aggiungi dispositivo manualmente",                "es": "Agregar dispositivo manualmente",                 "pl": "Dodaj urządzenie ręcznie",                        "zh-cn": "手动添加设备"},
    "Automatic device detection activated": {        "en": "Automatic device detection activated",            "de": "Automatische Geräteerkennung aktiviert",          "ru": "Активировано автоматическое обнаружение устройства", "pt": "Detecção automática de dispositivo ativada",      "nl": "Automatische apparaat detectie geactiveerd",      "fr": "Détection automatique des appareils activée",     "it": "Rilevamento automatico del dispositivo attivato", "es": "Detección automática de dispositivos activada",   "pl": "Aktywowane automatyczne wykrywanie urządzeń",     "zh-cn": "自动设备检测已激活"},
    "Close": {                                       "en": "Close",                                           "de": "Schließen",                                       "ru": "Закрывать",                                       "pt": "Fechar",                                          "nl": "Sluiten zodra klaar",                             "fr": "Fermer",                                          "it": "Vicino",                                          "es": "Cerrar",                                          "pl": "Blisko",                                          "zh-cn": "关闭"},
    "Connected": {                                   "en": "Connected",                                       "de": "In Verbindung gebracht",                          "ru": "Связаны",                                         "pt": "Conectado",                                       "nl": "Verbonden",                                       "fr": "Lié",                                             "it": "Collegato",                                       "es": "Conectado",                                       "pl": "Połączony",                                       "zh-cn": "连接的"},
    "Delete": {                                      "en": "Delete",                                          "de": "Löschen",                                         "ru": "Удалить",                                         "pt": "Excluir",                                         "nl": "Verwijderen",                                     "fr": "Effacer",                                         "it": "Elimina",                                         "es": "Borrar",                                          "pl": "Kasować",                                         "zh-cn": "删除"},
    "Devices can be added manually or by autodiscovery": {"en": "Devices can be added manually or by autodiscovery", "de": "Geräte können manuell oder durch automatische Erkennung hinzugefügt werden", "ru": "Устройства можно добавлять вручную или с помощью автообнаружения", "pt": "Os dispositivos podem ser adicionados manualmente ou por autodiscovery", "nl": "Apparaten kunnen handmatig of door autodiscovery worden toegevoegd", "fr": "Les appareils peuvent être ajoutés manuellement ou par découverte automatique", "it": "I dispositivi possono essere aggiunti manualmente o tramite rilevamento automatico", "es": "Los dispositivos se pueden agregar manualmente o por descubrimiento automático", "pl": "Urządzenia można dodawać ręcznie lub przez automatyczne wykrywanie", "zh-cn": "可以手动添加设备或通过自动发现添加设备"},
    "Edit": {                                        "en": "Edit",                                            "de": "Bearbeiten",                                      "ru": "Редактировать",                                   "pt": "Editar",                                          "nl": "Bewerk",                                          "fr": "Éditer",                                          "it": "modificare",                                      "es": "Editar",                                          "pl": "Edytować",                                        "zh-cn": "编辑"},
    "Edit device": {                                 "en": "Edit device",                                     "de": "Gerät bearbeiten",                                "ru": "Изменить устройство",                             "pt": "Editar dispositivo",                              "nl": "Bewerk apparaat",                                 "fr": "Modifier l'appareil",                             "it": "Modifica dispositivo",                            "es": "Editar dispositivo",                              "pl": "Edytuj urządzenie",                               "zh-cn": "编辑装置"},
    "ID": {                                          "en": "ID",                                              "de": "ID",                                              "ru": "Я БЫ",                                            "pt": "EU IA",                                           "nl": "ID",                                              "fr": "identifiant",                                     "it": "ID",                                              "es": "IDENTIFICACIÓN",                                  "pl": "ID",                                              "zh-cn": "ID"},
    "IP": {                                          "en": "IP",                                              "de": "IP",                                              "ru": "IP",                                              "pt": "IP",                                              "nl": "IP",                                              "fr": "IP",                                              "it": "IP",                                              "es": "IP",                                              "pl": "IP",                                              "zh-cn": "知识产权"},
    "IP-Address": {                                  "en": "IP-Address",                                      "de": "IP Adresse",                                      "ru": "Айпи адрес",                                      "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adresse IP",                                      "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "Имя",                                             "pt": "Nome",                                            "nl": "Naam",                                            "fr": "Nom",                                             "it": "Nome",                                            "es": "Nombre",                                          "pl": "Nazwa",                                           "zh-cn": "姓名"},
    "device-pass": {                                 "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "reconnect interval": {                          "en": "Reconnect Interval",                              "de": "Intervall für erneutes Verbinden",                "ru": "интервал повторного подключения",                 "pt": "intervalo de reconexão",                          "nl": "interval voor opnieuw verbinden",                 "fr": "intervalle de reconnexion",                       "it": "ricollegare l'intervallo",                        "es": "intervalo de reconexión",                         "pl": "interwał ponownego łączenia",                     "zh-cn": "重新连接间隔"},
};